# Generated by Django 5.0.1 on 2024-01-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSignup', '0002_usersignup_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
    ]
