# Generated by Django 5.0.1 on 2024-01-11 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookingdetails',
            table=None,
        ),
    ]
