# Generated by Django 5.0.1 on 2024-01-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingPage', '0002_alter_bookingdetails_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
