# Generated by Django 5.0.1 on 2024-01-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingPage', '0003_alter_bookingdetails_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingDetails',
        ),
    ]
