# Generated by Django 5.0.1 on 2024-01-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0002_remove_bookingdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='time',
            field=models.TimeField(),
        ),
    ]
