# Generated by Django 5.0.1 on 2024-01-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSignup', '0002_remove_adminsignup_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsignup',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adminsignup',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
